# Generated by Django 5.0.1 on 2024-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0002_manufacturer_alter_product_qty_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Каталожный номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
